os: linux

language: go

go:
  - 1.16.2

services:
  - postgresql

#env:
#  - APP_DB_USERNAME=postgres

script:
  # Test the code
  - go test -v ./...
  # Build the code
  - CGO_ENABLED=0 GOARCH=amd64 go build -o ms_demo
