os: linux

language: go

go:
  - 1.16.2

services:
  - postgresql
  - docker

script:
  # Test the code
  - go test -v ./...
  # Build the code
  - CGO_ENABLED=0 GOARCH=amd64 go build -o ms_demo
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t johannager/demo:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag johannager/demo:latest johannager/demo:$GIT_SHA
  - docker push johannager/demo:latest
  - docker push johannager/demo:$GIT_SHA
